name: Go

on:
  push:
    branches: [ devel, auto ]
  pull_request:
    branches: [ devel, auto ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - /var/lib/database/mysql:/var/lib/mysql
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: admin@12345

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
